services:
  lolplatform:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "8501:8501"  #  Streamlit
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lolplatform_db
    ports:
      - "5432:5432"  # Solo expone PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
